### ISSUE TITLE
A buyer should be able to leave feedback for products

### ISSUE THREAD

**Issue by UwicyezaG** [atlp-rwanda/knights-ecomm-be#105]
### Description

This feature will allow buyers to leave feedback on products they have purchased, which will help future buyers to make informed decisions. This feedback will be visible to all users who access the product page, including buyers, vendors, and admins. Buyers will have the capability to create, update, and delete their feedback. Admins will have the ability to view and delete any feedback, while vendors will only be able to view the feedback.

### Functionalities

- Buyers can leave feedback on products they have purchased.
- Buyers can manage the feedback by updating and deleting them.
- All users that view product page.
- Admin management can view and delete any feedback.

### Acceptance Criteria 

- A logged-in buyer can submit feedback on a product.
- Buyers can update or delete their own feedback.
- Feedback is visible to all users who access the product page.
- Admins can view and delete any feedback and Vendor can only view the product.

### Definition of Done

- [ ] Backend API endpoints for creating, updating, viewing, and deleting feedback are implemented and functional.
- [ ] Validation is in place to ensure only logged-in buyers can leave, update, or delete their feedback.
- [ ] Admin controls for managing feedback are implemented.
- [ ] Tests are practiced to ensure the system works correctly and is easy to use.
- [ ] User feedback is collected and used to enhance the feedback system.

**Comment by UwicyezaG** [comment]
##  Implementation Plan 

#### 1. Develop API Endpoints: 

- Create Node.js route handlers for creating, updating, viewing, and deleting feedback.
- Implement Endpoints for feedback making, updation, removal, and retrieval.

#### 2. Feedback Submission

- Implement Logic to allow buyers to update and delete their feedback
- Ensure authentication and authorization checks.

#### 3. Admin Control

- Implement logic for admins to view and delete any feedback.
- Ensure proper authentication and authorization checks for admin actions.

#### Tests

- Write tests to validate the functionality of feedback submission, updating, viewing, and deletion.
- Test different situations like valid feedback submissions, unauthorized access, and admin management.

**Comment by faid-terence** [comment]
@elijahladdie and @UwicyezaG 
Attach the ERD !
