### ISSUE TITLE
Chore: Set Up Logging Library

### ISSUE THREAD

**Issue by GSinseswa721** [atlp-rwanda/knights-ecomm-be#28]
**Description**

As part of improving e-commerce system, I need to implement logging functionality using the Morgan library to monitor and track operations effectively.

**Tasks**

- [ ]  Install and set up the Morgan logging library in the project.
- [ ]  Configure logging levels .
- [ ]  Define appropriate output destinations for logs .
- [ ]  Integrate logging into relevant parts.
- [ ]  Implement error handling and logging .

**Acceptance Criteria**

-  Morgan logging library is successfully integrated into the project.
-  Logging levels are configured appropriately.
-  Logs are directed to specified output destinations.
-  Error handling includes logging of exceptions and error messages.

**Developer Notes**

Follow best practices for setting up logging Library and configure .

**Related Issues**
Test Coverage #11
