### ISSUE TITLE
Feat: Role-Based Access Control (RBAC)

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#45]
### Description

As an e-commerce platform, we want to implement role-based access control (RBAC) to ensure that users (admins, vendors, and buyers) have appropriate access to features and functionalities based on their roles and permissions.

### Acceptance Criteria

- [x] Define roles and permissions for vendors and buyers
- [x] Implement an API endpoint for managing roles and permissions
- [x] Assign roles and permissions to users during registration or profile update
- [x] Enforce role-based access control throughout the application
- [x] Implement appropriate error handling and responses
- [x] Write comprehensive unit tests

### Developer Notes

- Analyze the required roles and permissions for platform admins, vendors and buyers
- Design the data model and database schema for roles and permissions
- Define the API endpoint and request/response payloads for managing roles and permissions
- Integrate the RBAC system with the user authentication and authorization mechanisms
- Implement a middleware (or decorators) to enforce RBAC throughout the application
- Write unit tests to cover different scenarios and edge cases
- Write clear API documentation for the resulting endpoints

### Related Issues

- #xx link any related issue in this sprint

### Definition of Done

- Roles and permissions are defined for vendors and buyers
- API endpoint for managing roles and permissions is implemented and functional
- Roles and permissions are assigned to users during registration or profile update
- Role-based access control is enforced throughout the application
- Appropriate error handling and responses are implemented
- Comprehensive unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoints is completed

**Comment by aimedivin** [comment]
## Implementation Plan
### 1. Deliverables at the end of the project.

For Our application API when a user interacts with it there is an action(request) made. not all requests must be successfully fulfilled, because not all user have access to each and everything on our app. that’s why we set role and permissions to make sure a user is authorized for the action whenever he/she make request.
 
- Assigning role to a user being registered
- Implementation of role-based access control (RBAC) for admins, vendors, and buyers.
- API endpoint for managing roles and permissions.
- Integration of RBAC with user authentication and authorization mechanisms.
- Middleware to enforce RBAC throughout the application.
- Comprehensive unit tests covering different RBAC scenarios.
- Completed API documentation for the resulting endpoints.


#### DEV NOTE (REQUIRED)

Document code using JSDOC
Under activity, endeavor to come up with the thought process (data flow) needed to implement this feature.
Come up with the implementation plan for the the feature using the doc provided by your manager.
### 2. Data flow / Flowchart / pseudocode / ERD diagrams
![Screenshot from 2024-05-02 08-11-14](https://github.com/atlp-rwanda/knights-ecomm-be/assets/82057476/1e3cd42f-f8ac-4cc1-95bb-948980985fdf)

### 4. Schedule of implementation of the various parts
- Start the Implementation by Thursday (2nd/ 4/2024) 12h 
- Expected to Have all functionalities by Friday (3rd/05/2024) 16h
- Officially Have all functionalities not later than Sunday (5th/05/2024) 

### 5. Dependencies/Foreseen blockers from team members
- None for now

### 6. External services or libraries to be used.
- Express.js for API development.
- Jest for unit testing.
- TypeORM for database ORM.
- Swagger for API documentation and JSDOC.
