### ISSUE TITLE
Buyer-Order Tracking 

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-be#91]
### Description
 This backend is  to handle the checkout process, including validating and processing the order, updating inventory and updating the customer's account. 

### Functionalities

1. Make an order
   - Allow buyers to select products and add them to their chart.
   - Calculate the total amount by multiplying the product price with the quantity selected and as well add all products's prices to find the total amount.
   - Deduct the total amount from the buyer's account balance.
   - Send an email notification confirming the purchase, including details of product bought and payment made.
   - Update the order status on the application to transit.

2. Track order status
     
   - Enable buyer to track the status of their order.
   - Provide real-time updates on the order status, including if it is in transit or has arrived
   - Allow the buyer to confirm receipt of the product, marking the order status as delivered.
   - Facilitate product returns, updating the order status accordingly on the app. 

### Acceptance criteria
 
- Buyers can successfully make orders by adding products to their charts and completing the checkout process
- The total amount is calculated and deducted from the buyer's account balance
- Emails are sent to the buyers confirming their order on the application, with real-time updates on order status changes.
- Order status is updated to  show current stage of the delivery including in transit, delivered, returned.

### Definition of Done: 

- [ ]  Backend API endpoints for order processing and order tracking are implemented and functional.
- [ ]  Order processing logic  handles deductions from the buyer's account balance and updates inventory levels
- [ ]  Email notification system is integrated to send confirmations to buyers upon successful orders.
- [ ]  Real-time updates for order status tracking are implemented using various technology.
- [ ]  testing is conducted to ensure reliability and usability.
- [ ]  Feedback from buyers is gathered and incorporated to enhance the checkout and order tracking experience.

**Comment by elijahladdie** [comment]
@faid-terence  if this is everything about it ,
does it concern money or any transaction process?

**Comment by faid-terence** [comment]
@elijahladdie That's a sample of what you have to do , as an engineer you should now come up with a clear description and the implementation plan as well 
Make order - Buyer should be able to order products on our application
Track Order status - Buyer should be able to track status of their app .

**Comment by elijahladdie** [comment]
Okey We will work on it and look for better solution on that😊

**Comment by faid-terence** [comment]
But we need your Implementation plan and clear description of this issue by standup time !

**Comment by UwicyezaG** [comment]
## Implementation Plan

#### 1. Develop API Endpoints: 

-  Create Node.js routes to handle the checkout process, order tracking, and status updates.
- Implement endpoints for making orders, tracking order status, and handling the returns.

#### 2. Order Processing:

- Implement logic to validate and process orders.
- Update inventory levels according to the purchase quantity.
- Deduct the total from the buyer's account balance.
- Send an email confirming the purchase.

#### 3. Order Status Tracking:

- Integrate real-time updates for order status 
- Develop functionalities for buyers to track their orders on the app.
- Implement status updates for different stages of the order. if in transit, delivered, or returned

#### 4. Testing

- Write tests to validate the functionality of the checkout process and order tracking.
- Test different situations such as successful orders, cancelled order, and returns

#### 5. Feedback 

- Collect feedback from buyers

**Comment by faid-terence** [comment]
@UwicyezaG , @elijahladdie nice 
Now attach the ERD to show relations between order, product and user
